project:
  type: website

website:
  title: "Alyssa Columbus"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: example-analysis.qmd
        text: Example Analysis

format:
  html:
    theme: 
      light: yeti
      dark: cyborg
    css: styles.css
    toc: true

editor: visual

